<?php
/*
 * This file is part of wulacms.
 *
 * (c) Leo Ning <windywany@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace passport\classes\model;

use wulaphp\db\MetaTable;
use wulaphp\db\Table;

class PassportMeta extends Table {
    use MetaTable;
    private $metaIdField   = 'passport_id';
    private $metaNameField = 'name';

    public function get_field($passport_id, $name) {
        $res = $this->findOne(['passport_id' => $passport_id, 'name' => $name], 'value')[0];
        if ($res) {
            return $res['value'];
        }

        return false;
    }

    public function insertData($data, $cb = null) {
        return $this->insert($data, $cb); // TODO: Change the autogenerated stub
    }

    public function updateData($data = null, $con = null, $cb = null) {
        return $this->update($data, $con, $cb); // TODO: Change the autogenerated stub
    }

    public function insertsData($datas, \Closure $cb = null) {
        return $this->inserts($datas, $cb); // TODO: Change the autogenerated stub
    }

}